=== torsec/reachabilityanalysistool/xml_network.dtd
<!ELEMENT Network (Firewall+, FilteringZone+, Host+, Link+)>

<!ELEMENT Firewall (Interface+)>
<!ATTLIST Firewall
	Name CDATA #REQUIRED>
	
<!ELEMENT Host (Interface+, Service*)>
<!ATTLIST Host
	Name CDATA #REQUIRED
	FilteringZone IDREF #REQUIRED>
	
<!ELEMENT Interface EMPTY >	
<!ATTLIST Interface
	Name ID #REQUIRED
	IP CDATA #REQUIRED>
	
<!ELEMENT Service EMPTY>
<!ATTLIST Service 
	Name CDATA #REQUIRED
	IP CDATA #REQUIRED
	Port CDATA #REQUIRED>

<!ELEMENT FilteringZone EMPTY>
<!ATTLIST FilteringZone
	Name ID #REQUIRED
	Firewall IDREF #REQUIRED
	Subnet CDATA #REQUIRED>
	
<!ELEMENT Link EMPTY>
<!ATTLIST Link
	Endpoint1 IDREF #REQUIRED
	Endpoint2 IDREF #REQUIRED>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/Single/landscape.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Network SYSTEM "xml_network.dtd">
<Network>

     <Firewall Name="noConflict">
        <Interface Name="noConflict.eth0" IP="10.0.0.1"/>
        <Interface Name="noConflict.eth1" IP="10.0.1.1"/>
    </Firewall>  
    
    <Firewall Name="allConflict">
        <Interface Name="allConflict.eth0" IP="10.0.1.2"/>
        <Interface Name="allConflict.eth1" IP="10.0.2.1"/>
    </Firewall> 

 	<FilteringZone Name="noConflictZone" Firewall="noConflict.eth0" Subnet="10.0.0.0/24"/>
    <FilteringZone Name="allConflictZone" Firewall="allConflict.eth1" Subnet="10.0.2.0/24"/>
     
    <Host Name="s1" FilteringZone="noConflictZone">
        <Interface Name="s.eth0" IP="10.0.0.2" />
        <Service Name="http" IP="10.0.0.2" Port="80"/>                 
    </Host>

	<Link Endpoint1="noConflict.eth1" Endpoint2="allConflict.eth0" />


</Network>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/NAT/landscape.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Network SYSTEM "xml_network.dtd">
<Network>

     <Firewall Name="fw1">
        <Interface Name="fw1.eth0" IP="10.0.1.1"/>
        <Interface Name="fw1.eth1" IP="10.0.0.1"/>
        <Interface Name="fw1.eth2" IP="10.0.3.1"/>
    </Firewall>  
    
    <Firewall Name="fw2">
        <Interface Name="fw2.eth0" IP="10.0.0.2"/>
        <Interface Name="fw2.eth1" IP="10.0.2.1"/>
    </Firewall> 

    <FilteringZone Name="Zone1" Firewall="fw1.eth0" Subnet="10.0.1.0/24"/>
    <FilteringZone Name="Zone2" Firewall="fw2.eth1" Subnet="10.0.2.0/24"/>
    <FilteringZone Name="Zone3" Firewall="fw1.eth2" Subnet="10.0.3.0/24"/>
     
    <Host Name="s1" FilteringZone="Zone2">
        <Interface Name="s1.eth0" IP="10.0.2.12" />
        <Service Name="http" IP="10.0.2.12" Port="12"/>                 
    </Host>
    
    <Host Name="c1" FilteringZone="Zone1">
        <Interface Name="c1.eth0" IP="10.0.1.10" />               
    </Host>

    <Link Endpoint1="fw1.eth1" Endpoint2="fw2.eth0" />

</Network>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/landscape.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Network SYSTEM "xml_network.dtd">
<Network>

     <Firewall Name="fwA1">
        <Interface Name="fwA1.eth0" IP="10.1.1.1"/>
        <Interface Name="fwA1.eth1" IP="10.1.2.1"/>
        <Interface Name="fwA1.eth2" IP="10.1.0.1"/>
    </Firewall>  
    
    <Firewall Name="fwA2">
        <Interface Name="fwA2.eth0" IP="10.1.0.3"/>
        <Interface Name="fwA2.eth1" IP="10.1.0.5"/>
        <Interface Name="fwA2.eth2" IP="10.1.0.7"/>
    </Firewall> 
    
    <Firewall Name="fwA3">
        <Interface Name="fwA3.eth0" IP="10.1.0.6"/>
        <Interface Name="fwA3.eth1" IP="10.1.3.1"/>
        <Interface Name="fwA3.eth2" IP="10.1.4.1"/>
        <Interface Name="fwA3.eth3" IP="10.1.0.9"/>
    </Firewall> 
    
    <Firewall Name="fwA4">
        <Interface Name="fwA4.eth0" IP="10.1.5.1"/>
        <Interface Name="fwA4.eth1" IP="10.1.6.1"/>
        <Interface Name="fwA4.eth2" IP="10.1.0.8"/>
        <Interface Name="fwA4.eth3" IP="10.1.0.10"/>
    </Firewall>
    
    <Firewall Name="fwB1">
        <Interface Name="fwB1.eth0" IP="10.2.0.2"/>
        <Interface Name="fwB1.eth1" IP="10.2.0.9"/>
        <Interface Name="fwB1.eth2" IP="10.2.0.3"/>
        <Interface Name="fwB1.eth3" IP="10.2.0.5"/>
        <Interface Name="fwB1.eth4" IP="10.2.3.1"/>
    </Firewall>
    
    <Firewall Name="fwB2">
        <Interface Name="fwB2.eth0" IP="10.2.0.4"/>
        <Interface Name="fwB2.eth1" IP="10.2.0.7"/>
        <Interface Name="fwB2.eth2" IP="10.2.4.1"/>
        <Interface Name="fwB2.eth3" IP="10.2.5.1"/>
        <Interface Name="fwB2.eth4" IP="10.2.6.1"/>
        <Interface Name="fwB2.eth5" IP="10.2.7.1"/>
    </Firewall> 
    
    <Firewall Name="fwB3">
        <Interface Name="fwB3.eth0" IP="10.2.0.6"/>
        <Interface Name="fwB3.eth1" IP="10.2.0.8"/>
        <Interface Name="fwB3.eth2" IP="10.2.1.1"/>
        <Interface Name="fwB3.eth3" IP="10.2.2.1"/>
    </Firewall>  
    
    <Firewall Name="fwC1">
        <Interface Name="fwC1.eth0" IP="10.3.0.1"/>
        <Interface Name="fwC1.eth1" IP="10.2.0.10"/>
        <Interface Name="fwC1.eth2" IP="10.3.0.3"/>
        <Interface Name="fwC1.eth3" IP="10.3.0.4"/>
    </Firewall>
    
    <Firewall Name="fwC2">
        <Interface Name="fwC2.eth0" IP="10.3.0.5"/>
        <Interface Name="fwC2.eth1" IP="10.3.1.1"/>
        <Interface Name="fwC2.eth2" IP="10.3.2.1"/>
    </Firewall>
    
    <Firewall Name="fwC3">
        <Interface Name="fwC3.eth0" IP="10.3.0.6"/>
        <Interface Name="fwC3.eth1" IP="10.3.3.1"/>
        <Interface Name="fwC3.eth2" IP="10.3.4.1"/>
    </Firewall>      
  
    <Firewall Name="rA">
        <Interface Name="rA.eth0" IP="10.1.0.2"/>  
        <Interface Name="rA.eth1" IP="10.1.0.4"/>
        <Interface Name="rA.eth2" IP="10.2.0.1"/>
        <Interface Name="rA.eth3" IP="10.3.0.1"/>
    </Firewall>

 	<FilteringZone Name="ZA1" Firewall="fwA1.eth0" Subnet="10.1.1.0/24"/>
    <FilteringZone Name="ZA2" Firewall="fwA1.eth1" Subnet="10.1.2.0/24"/>
    <FilteringZone Name="ZA3" Firewall="fwA3.eth1" Subnet="10.1.3.0/24"/>
    <FilteringZone Name="ZA4" Firewall="fwA3.eth2" Subnet="10.1.4.0/24"/>
    <FilteringZone Name="ZA5" Firewall="fwA4.eth0" Subnet="10.1.5.0/24"/>
    <FilteringZone Name="ZA6" Firewall="fwA4.eth1" Subnet="10.1.6.0/24"/>
    <FilteringZone Name="ZB1" Firewall="fwB3.eth2" Subnet="10.2.1.0/24"/>
    <FilteringZone Name="ZB2" Firewall="fwB3.eth3" Subnet="10.2.2.0/24"/>
    <FilteringZone Name="ZB3" Firewall="fwB1.eth4" Subnet="10.2.3.0/24"/>
    <FilteringZone Name="ZB4" Firewall="fwB2.eth2" Subnet="10.2.4.0/24"/>
    <FilteringZone Name="ZB5" Firewall="fwB2.eth3" Subnet="10.2.5.0/24"/>
    <FilteringZone Name="ZB6" Firewall="fwB2.eth4" Subnet="10.2.6.0/24"/>
    <FilteringZone Name="ZB7" Firewall="fwB2.eth5" Subnet="10.2.7.0/24"/>
    <FilteringZone Name="ZC1" Firewall="fwC2.eth1" Subnet="10.3.1.0/24"/>
    <FilteringZone Name="ZC2" Firewall="fwC2.eth2" Subnet="10.3.2.0/24"/>
    <FilteringZone Name="ZC3" Firewall="fwC3.eth1" Subnet="10.3.3.0/24"/>
    <FilteringZone Name="ZC4" Firewall="fwC3.eth2" Subnet="10.3.4.0/24"/>
     
    <Host Name="c_a1_1" FilteringZone="ZA1">
        <Interface Name="c_a1_1.eth0" IP="10.1.1.2" />                 
    </Host>
    
    <Host Name="s_a5_1" FilteringZone="ZA5">
        <Interface Name="s_a5_1.eth0" IP="10.1.5.2" />
        <Service Name="http" IP="10.1.5.2" Port="80"/>                 
    </Host>
    
    <Host Name="s_b2_1" FilteringZone="ZB2">
        <Interface Name="s_b2_1.eth0" IP="10.2.2.2" />
        <Service Name="http" IP="10.2.2.2" Port="80"/>                 
    </Host>
    
    <Host Name="s_c3_1" FilteringZone="ZC3">
        <Interface Name="s_c3_1.eth0" IP="10.3.3.2" />
        <Service Name="http" IP="10.3.3.2" Port="80"/>                 
    </Host>

	<Link Endpoint1="rA.eth0" Endpoint2="fwA1.eth2" />
	<Link Endpoint1="rA.eth1" Endpoint2="fwA2.eth0" />
	<Link Endpoint1="rA.eth2" Endpoint2="fwB1.eth0" />
	<Link Endpoint1="rA.eth3" Endpoint2="fwC1.eth0" />
	<Link Endpoint1="fwA2.eth1" Endpoint2="fwA3.eth0" />
	<Link Endpoint1="fwA3.eth3" Endpoint2="fwA4.eth3" />
	<Link Endpoint1="fwC1.eth1" Endpoint2="fwB1.eth1" />
	<Link Endpoint1="fwC1.eth2" Endpoint2="fwC2.eth0" />
	<Link Endpoint1="fwC1.eth3" Endpoint2="fwC3.eth0" />
	<Link Endpoint1="fwB1.eth2" Endpoint2="fwB2.eth0" />
	<Link Endpoint1="fwB1.eth3" Endpoint2="fwB3.eth0" />
	<Link Endpoint1="fwB2.eth1" Endpoint2="fwB3.eth3" />

</Network>
