=== torsec/reachabilityanalysistool/it.polito.policytoollib/src/it/polito/policytoollib/wrapper/xml_policy.dtd
<!ELEMENT Policy (PolicyName, PolicyType, Resolver , ExternalDataClass , DefAction , Rule*)>
<!ELEMENT PolicyName (#PCDATA) >
<!ELEMENT PolicyType (#PCDATA) >
<!ELEMENT Resolver (#PCDATA) >
<!ELEMENT ExternalDataClass (#PCDATA) >
<!ELEMENT DefAction (#PCDATA) >


<!ELEMENT Rule (ExternalDataValue? , Selector+, Transformation?, ActionData*) >
<!ATTLIST Rule 
	Action ( ALLOW | DENY | AH | INVERT_AH | ESP | INVERT_ESP | PRENAT | POSTNAT | LOGGING ) #REQUIRED
	Label CDATA #IMPLIED>
<!ELEMENT ExternalDataValue (#PCDATA) >

<!ELEMENT Transformation (Selector+) >

<!ELEMENT ActionData EMPTY>
<!ATTLIST ActionData
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED>
	
<!ELEMENT Selector (#PCDATA) >
<!ATTLIST Selector
	Label CDATA #REQUIRED>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/secure/fwC3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fwC3</PolicyName>
<PolicyType>VPN</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="INVERT_ESP" Label="fwC3.INVERT_ESP1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.3.0.4-10.3.0.4</Selector>
<Selector Label="Destination Address">10.3.0.6-10.3.0.6</Selector>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/InterDistributed/policy/fw2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fw2</PolicyName>
<PolicyType>LOGGING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>ALLOW</DefAction>

<Rule Action="LOGGING" Label="fw2.R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Port">10-20</Selector>
<Selector Label="Destination Port">10-20</Selector>
</Rule>

<Rule Action="LOGGING" Label="fw2.R2">
<ExternalDataValue>2</ExternalDataValue>
<Selector Label="Source Port">30-40</Selector>
<Selector Label="Destination Port">30-40</Selector>
</Rule>

<Rule Action="LOGGING" Label="fw2.R3">
<ExternalDataValue>3</ExternalDataValue>
<Selector Label="Source Port">50-60</Selector>
<Selector Label="Destination Port">50-60</Selector>
</Rule>

<Rule Action="LOGGING" Label="fw2.R4">
<ExternalDataValue>4</ExternalDataValue>
<Selector Label="Source Port">70-80</Selector>
<Selector Label="Destination Port">70-80</Selector>
</Rule>


</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/Distributed/policy/fw2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fw2</PolicyName>
<PolicyType>FILTERING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ALLOW" Label="fw2.R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Port">11-20</Selector>
<Selector Label="Destination Port">10-20</Selector>
</Rule>

<Rule Action="DENY" Label="fw2.R2">
<ExternalDataValue>2</ExternalDataValue>
<Selector Label="Source Port">21-30</Selector>
<Selector Label="Destination Port">10-20</Selector>
</Rule>




<Rule Action="DENY" Label="fw2.R4">
<ExternalDataValue>4</ExternalDataValue>
<Selector Label="Source Port">31-40</Selector>
<Selector Label="Destination Port">30-40</Selector>
</Rule>

<Rule Action="DENY" Label="fw2.R5">
<ExternalDataValue>5</ExternalDataValue>
<Selector Label="Source Port">41-50</Selector>
<Selector Label="Destination Port">30-40</Selector>
</Rule>



<Rule Action="ALLOW" Label="fw2.R6">
<ExternalDataValue>6</ExternalDataValue>
<Selector Label="Source Port">51-60</Selector>
<Selector Label="Destination Port">50-60</Selector>
</Rule>

<Rule Action="DENY" Label="fw2.R7">
<ExternalDataValue>7</ExternalDataValue>
<Selector Label="Source Port">61-70</Selector>
<Selector Label="Destination Port">55-65</Selector>
</Rule>

<Rule Action="ALLOW" Label="fw2.R8">
<ExternalDataValue>8</ExternalDataValue>
<Selector Label="Source Port">71-80</Selector>
<Selector Label="Destination Port">75-75</Selector>
</Rule>

<Rule Action="DENY" Label="fw2.R9">
<ExternalDataValue>9</ExternalDataValue>
<Selector Label="Source Port">81-90</Selector>
<Selector Label="Destination Port">70-80</Selector>
</Rule>



</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/policy/fwA3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fwA3</PolicyName>
<PolicyType>FILTERING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ALLOW" Label="fwA3_R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.1.0.5-10.1.0.7</Selector>
<Selector Label="Destination Address">10.1.0.7-10.1.0.7</Selector>
</Rule>


</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/VPN/secure/fw1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fw1</PolicyName>
<PolicyType>VPN</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ESP" Label="fw1.PRENAT1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Port">11-11</Selector>
<Selector Label="Destination Port">11-11</Selector>
<Selector Label="Source Address">10.0.1.11-10.0.1.11</Selector>
<Selector Label="Destination Address">10.0.2.11-10.0.2.11</Selector>
<Transformation>
	<Selector Label="Source Port">12-12</Selector>
	<Selector Label="Destination Port">12-12</Selector>
	<Selector Label="Source Address">10.0.1.12-10.0.1.12</Selector>
	<Selector Label="Destination Address">10.0.2.12-10.0.2.12</Selector>
</Transformation>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/nat/fwB1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fwB1</PolicyName>
<PolicyType>NAT</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="POSTNAT" Label="fwB1.POSTNAT1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.1.1.0-10.1.1.255</Selector>
<Selector Label="Destination Address">10.2.0.0-10.2.255.255</Selector>
<Transformation>
	<Selector Label="Source Address">10.2.0.5-10.2.0.5</Selector>
</Transformation>
</Rule>

<Rule Action="POSTNAT" Label="fwB1.POSTNAT2">
<ExternalDataValue>2</ExternalDataValue>
<Selector Label="Source Address">10.2.0.10-10.2.0.10</Selector>
<Selector Label="Destination Address">10.2.0.0-10.2.255.255</Selector>
<Transformation>
	<Selector Label="Source Address">10.2.0.5-10.2.0.5</Selector>
</Transformation>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/Single/policy/noConflict.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>noConflict</PolicyName>
<PolicyType>FILTERING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ALLOW" Label="R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Port">11-20</Selector>
<Selector Label="Destination Port">10-20</Selector>
</Rule>

<Rule Action="DENY" Label="R2">
<ExternalDataValue>2</ExternalDataValue>
<Selector Label="Source Port">21-30</Selector>
<Selector Label="Destination Port">10-20</Selector>
</Rule>




<Rule Action="DENY" Label="R4">
<ExternalDataValue>4</ExternalDataValue>
<Selector Label="Source Port">31-40</Selector>
<Selector Label="Destination Port">30-40</Selector>
</Rule>

<Rule Action="DENY" Label="R5">
<ExternalDataValue>5</ExternalDataValue>
<Selector Label="Source Port">41-50</Selector>
<Selector Label="Destination Port">30-40</Selector>
</Rule>



<Rule Action="ALLOW" Label="R6">
<ExternalDataValue>6</ExternalDataValue>
<Selector Label="Source Port">51-60</Selector>
<Selector Label="Destination Port">50-60</Selector>
</Rule>

<Rule Action="DENY" Label="R7">
<ExternalDataValue>7</ExternalDataValue>
<Selector Label="Source Port">61-70</Selector>
<Selector Label="Destination Port">55-65</Selector>
</Rule>

<Rule Action="ALLOW" Label="R8">
<ExternalDataValue>8</ExternalDataValue>
<Selector Label="Source Port">71-80</Selector>
<Selector Label="Destination Port">75-75</Selector>
</Rule>

<Rule Action="DENY" Label="R9">
<ExternalDataValue>9</ExternalDataValue>
<Selector Label="Source Port">81-90</Selector>
<Selector Label="Destination Port">70-80</Selector>
</Rule>



</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/out.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>TestPolicy</PolicyName>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>
<Rule Action="ALLOW" Label="R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.1.1.0-10.1.1.255</Selector>
<Selector Label="Destination Address">10.1.5.2-10.1.5.2</Selector>
<Selector Label="Source Port">80-80</Selector>
<Selector Label="Destination Port">80-80</Selector>
<Selector Label="Protocol Type">IP</Selector>
<Selector Label="L4Protocol">TCP</Selector>
<Selector Label="Http Method">GET</Selector>
<Selector Label="Direction">IN</Selector>
<Selector Label="Time">S 10:10-S 10:10</Selector>
<Selector Label="RegExp">test</Selector>
<Selector Label="StateFull">ACK</Selector>
</Rule>
<Rule Action="DENY" Label="R2">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.1.1.0-10.1.1.0</Selector>
<Selector Label="Destination Address">10.1.5.2-10.1.5.2</Selector>
<Selector Label="Source Port">80-80</Selector>
<Selector Label="Destination Port">80-80</Selector>
<Selector Label="Protocol Type">IP;IPv6</Selector>
<Selector Label="L4Protocol">TCP;UDP</Selector>
<Selector Label="Http Method">GET;POST</Selector>
<Selector Label="Direction">IN;OUT</Selector>
<Selector Label="Time">S 10:10-S 10:10;M 10:10-M 12:0</Selector>
<Selector Label="RegExp">test</Selector>
<Selector Label="StateFull">ACK;SYN</Selector>
</Rule>
</Policy>
