=== torsec/reachabilityanalysistool/it.polito.policytoollib/src/it/polito/policytoollib/wrapper/xml_policy.dtd
<!ELEMENT Policy (PolicyName, PolicyType, Resolver , ExternalDataClass , DefAction , Rule*)>
<!ELEMENT PolicyName (#PCDATA) >
<!ELEMENT PolicyType (#PCDATA) >
<!ELEMENT Resolver (#PCDATA) >
<!ELEMENT ExternalDataClass (#PCDATA) >
<!ELEMENT DefAction (#PCDATA) >


<!ELEMENT Rule (ExternalDataValue? , Selector+, Transformation?, ActionData*) >
<!ATTLIST Rule 
	Action ( ALLOW | DENY | AH | INVERT_AH | ESP | INVERT_ESP | PRENAT | POSTNAT | LOGGING ) #REQUIRED
	Label CDATA #IMPLIED>
<!ELEMENT ExternalDataValue (#PCDATA) >

<!ELEMENT Transformation (Selector+) >

<!ELEMENT ActionData EMPTY>
<!ATTLIST ActionData
	Name CDATA #REQUIRED
	Value CDATA #REQUIRED>
	
<!ELEMENT Selector (#PCDATA) >
<!ATTLIST Selector
	Label CDATA #REQUIRED>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/policy/fwB3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fwB3</PolicyName>
<PolicyType>FILTERING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ALLOW" Label="fwB3_R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.2.0.5-10.2.0.5</Selector>
<Selector Label="Destination Address">10.2.2.2-10.2.2.2</Selector>
<Selector Label="Destination Port">80-80</Selector>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/InterDistributed/nat/fw1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fw1</PolicyName>
<PolicyType>NAT</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="POSTNAT" Label="fw1.POST1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Port">50-60</Selector>
<Selector Label="Destination Port">50-60</Selector>
<Transformation>
<Selector Label="Source Port">70-80</Selector>
<Selector Label="Destination Port">70-80</Selector>
</Transformation>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/PolitoNET/nat/fwDIP9.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fw1</PolicyName>
<PolicyType>NAT</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="PRENAT" Label="fw1.PRENAT1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.0.1.0-10.0.1.255</Selector>
<Transformation>
	<Selector Label="Source Address">10.0.0.1-10.0.0.1</Selector>
</Transformation>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/secure/fwA2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fwA2</PolicyName>
<PolicyType>VPN</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ESP" Label="fwA2.ESP1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.1.1.0-10.1.1.255</Selector>
<Selector Label="Destination Address">10.1.5.0-10.1.5.255</Selector>
<Transformation>
	<Selector Label="Source Address">10.1.0.5-10.1.0.5</Selector>
	<Selector Label="Destination Address">10.1.0.7-10.1.0.7</Selector>
</Transformation>
</Rule>

</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/NAT/policy/fw2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fw2</PolicyName>
<PolicyType>FILTERING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ALLOW" Label="fw2.R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Destination Port">12-12</Selector>
<Selector Label="Source Address">10.0.1.0-10.0.1.255</Selector>
<Selector Label="Destination Address">10.0.2.12-10.0.2.12</Selector>
</Rule>


</Policy>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/TestCases/ReadXML/policy/fwC1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy.dtd">
<Policy>
<PolicyName>fwC1</PolicyName>
<PolicyType>FILTERING</PolicyType>
<Resolver>it.polito.policytoollib.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>

<Rule Action="ALLOW" Label="fwC1_R1">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Source Address">10.1.0.1-10.1.0.1</Selector>
<Selector Label="Destination Address">10.3.0.6-10.3.0.6</Selector>
</Rule>

<Rule Action="ALLOW" Label="fwC1_R2">
<ExternalDataValue>2</ExternalDataValue>
<Selector Label="Source Address">10.1.1.0-10.1.1.255</Selector>
<Selector Label="Destination Address">10.2.2.2-10.2.2.2</Selector>
<Selector Label="Destination Port">80-80</Selector>
</Rule>

</Policy>
