=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/config_files/test/xml_policy_nat.dtd
<!ELEMENT Policy (Resolver , ExternalDataClass , DefAction , Rule+)>
<!ELEMENT Resolver (#PCDATA) >
<!ELEMENT ExternalDataClass (#PCDATA) >
<!ELEMENT DefAction (#PCDATA) >
<!ELEMENT RuleIdentifier (#PCDATA) >


<!ELEMENT Rule (ExternalDataValue? , Selector+) >
<!ATTLIST Rule 
	Action ( ALLOW | DENY | AH | INVERT_AH | ESP | INVERT_ESP | PRENAT | POSTNAT) #REQUIRED
	Label CDATA #IMPLIED
	RuleIdentifier CDATA #REQUIRED>
<!ELEMENT ExternalDataValue (#PCDATA) >

<!ELEMENT Selector (#PCDATA) >
<!ATTLIST Selector
	Label CDATA #REQUIRED>

=== torsec/reachabilityanalysistool/it.polito.policytoollib.test/config_files/fw0.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Policy SYSTEM "xml_policy_nat.dtd">
<Policy>
<Resolver>org.polito.policyManagement.policy.resolution.impl.FMRResolutionStrategy</Resolver>
<ExternalDataClass>java.lang.Integer</ExternalDataClass>
<DefAction>DENY</DefAction>
<Rule Action="ALLOW" Label="fw0_1" RuleIdentifier="3">
<ExternalDataValue>1</ExternalDataValue>
<Selector Label="Destination Port">80-80</Selector>
<Selector Label="Source Address">1.1.1.0-1.1.1.255</Selector>
<Selector Label="Destination Address">3.3.3.0-3.3.3.255</Selector>
</Rule>
<Rule Action="ALLOW" Label="fw0_2" RuleIdentifier="3">
<ExternalDataValue>2</ExternalDataValue>
<Selector Label="Destination Port">80-80</Selector>
<Selector Label="Source Address">2.2.2.0-2.2.2.255</Selector>
<Selector Label="Destination Address">4.4.4.0-4.4.4.255</Selector>
</Rule>
</Policy>
